### ISSUE TITLE
Automate GeoLite2 update

### ISSUE THREAD

**Issue by gravesm** [MITLibraries/oastats-backend#27]
Currently, the database is manually upgraded before every pipeline run. This process needs automating.

**Comment by JPrevost** [comment]
This may be something to consider incorporating.
http://dev.maxmind.com/geoip/geoipupdate/

**Comment by gravesm** [comment]
I'm not thinking of anything fancy here, probably just piping the output of curl to tar. Using their update tool would require either installing the package or compiling from source. I'd like to avoid having this dependency on production. The url where the database lives seems to always point to the latest version, so it should be straightforward to just grab it.

**Comment by JPrevost** [comment]
Yeah, for our purposes we won't be running this enough to want to deal with that dependency.

**Comment by gravesm** [comment]
Closing this issue as it is handled in the ansible playbook.
